### ISSUE TITLE
Metrics are not collected on Air-Gapped environment

### ISSUE THREAD

**Issue by DomR22** [sassoftware/viya4-monitoring-kubernetes#635]
Hello,

We have deployed Monitoring and Logging on Air-gapped environment (on GKE cluster) and the logging components are working as expected, the logs are showing correctly but the Metrics on Grafana are not collected as you can see:

![image](https://github.com/sassoftware/viya4-monitoring-kubernetes/assets/74821177/3875cb25-199b-440c-bc53-793f9c50ff78)

This is my user.env on monitoring path:

$USER_DIR/monitoring/user.env:

```
cat $USER_DIR/monitoring/user.env
MON_TLS_PATH_INGRESS=true
GRAFANA_ADMIN_PASSWORD=XXXXXX
NGINX_NS=ingress-entlakegcp-fc-svil
MON_NODE_PLACEMENT_ENABLE=true
```

And my $USER_DIR/user.env:

```
cat $USER_DIR/user.env
AIRGAP_DEPLOYMENT=true
AIRGAP_REGISTRY="xxxxxx"
AIRGAP_IMAGE_PULL_SECRET_NAME=v4m-image-pull-secret
LOG_DEBUG_ENABLE=true
AIRGAP_HELM_FORMAT=tgz
AIRGAP_HELM_REPO=/sas/helm-charts
```

And my $USER_DIR/monitoring/user-values-prom-operator.yaml :

```
cat $USER_DIR/monitoring/user-values-prom-operator.yaml
grafana:
  # Disable default configuration of NodePort
  service:
    type: ClusterIP
    nodePort: null
  ingress:
    ingressClassName: entlakegcp-fc-svil
    annotations:
      nginx.ingress.kubernetes.io/backend-protocol: HTTPS
      kubernetes.io/ingress.class: entlakegcp-fc-svil
    enabled: true
    tls:
    - hosts:
      - fe-analitico.edlsvil.telecomitalia.local
      secretName: grafana-ingress-tls-secret
    hosts:
    - fe-analitico.edlsvil.telecomitalia.local
    path: /grafana
    pathType: Prefix
  "grafana.ini":
    server:
      domain: fe-analitico.edlsvil.telecomitalia.local
      root_url: https://fe-analitico.edlsvil.telecomitalia.local/grafana
      serve_from_sub_path: true

# This sample does NOT expose Prometheus and Alertmanager via Ingress by default.
# However, you can expose one or both of these web applications
# by changing the 'ingress.enabled' key from 'false' to 'true'
# in the 'prometheus' and/or 'alertmanager' stanza below


# Note that Prometheus and Alertmanager
# do not have any authentication configured by default, and exposing
# an unauthenticated applicaton without other restrictions in place
# is insecure.

prometheus:
  # Disable default configuration of NodePort
  service:
    type: ClusterIP
    nodePort: null
  # Define path-based ingress
  ingress:
    # change the following value to 'true'
    # to make Prometheus accessible via ingress
    enabled: false
    ingressClassName: entlakegcp-fc-svil
    annotations:
      nginx.ingress.kubernetes.io/backend-protocol: HTTPS
    tls:
    - hosts:
      - fe-analitico.edlsvil.telecomitalia.local
      secretName: prometheus-ingress-tls-secret
    hosts:
    - fe-analitico.edlsvil.telecomitalia.local
    path: /prometheus
    pathType: Prefix
  prometheusSpec:
    routePrefix: /prometheus
    externalUrl: https://fe-analitico.edlsvil.telecomitalia.local/prometheus
    alertingEndpoints:
      - name: v4m-alertmanager
        port: http-web
        pathPrefix: "/alertmanager"
        scheme: https
        tlsConfig:
          insecureSkipVerify: true

alertmanager:
  # Disable default configuration of NodePort
  service:
    type: ClusterIP
    nodePort: null
  # Define path-based ingress
  ingress:
    # change the following value to 'true'
    # to make Alertmanager accessible via ingress
    enabled: false
    ingressClassName: entlakegcp-fc-svil
    annotations:
      nginx.ingress.kubernetes.io/backend-protocol: HTTPS
    tls:
    - hosts:
      - fe-analitico.edlsvil.telecomitalia.local
      secretName: alertmanager-ingress-tls-secret
    hosts:
    - fe-analitico.edlsvil.telecomitalia.local
    path: /alertmanager
    pathType: Prefix
  alertmanagerSpec:
    routePrefix: /alertmanager
    externalUrl: https://fe-analitico.edlsvil.telecomitalia.local/alertmanager
```

The deployment commands seems to be fine since that i have not any errors, i can access to grafana correctly but prometheus do not show any data on the SAS Viya Dashboards or any Kubernetes Cluster Dashboard.

Can you help me to resolve this issue?

Thanks,
Domenico

**Comment by DomR22** [comment]
In addition, seems that the metrics filter didn't loaded on Grafana:

![image](https://github.com/sassoftware/viya4-monitoring-kubernetes/assets/74821177/57d008ca-3c06-4b81-ba6b-a8a51490e03b)

![image](https://github.com/sassoftware/viya4-monitoring-kubernetes/assets/74821177/db84d249-9155-492c-a310-83595fc5f04f)

**Comment by DomR22** [comment]
In addition seems that the serviceMonitor of Sas Viya cannot scraped as the screenshot below:

![image](https://github.com/sassoftware/viya4-monitoring-kubernetes/assets/74821177/126f7de9-ff5f-4407-9c0e-91779ff286f4)

Can you please help us?
Thanks

**Comment by gsmith-sas** [comment]
@DomR22   Is it only the SAS Viya-related metrics that are not working? Are there metrics on the non-SAS dashboards, like the Kubernetes Cluster dashboard?  If it is only the SAS Viya-related metrics, did you run the deploy_monitoring_viya.sh script?  It deploys instrumentation that allows Prometheus to collect metrics from SAS Viya components.  It is a separate script from the deploy_monitoring_cluster.sh script which deploys the cluster-level components such as Prometheus and Grafana.

The "content deadline exceeded" messages shown in the screenshot indicates that Prometheus did NOT get a response before timing out.  That could be due to a firewall blocking traffic between Prometheus and the other pods running on the cluster.  We have seen similar problems on Microsoft Azure clusters with the Azure Web Application Firewall (WAF) deployed.  To fix that, the WAF firewalls had to be adjusted to allow Prometheus to talk with the other components.  I'm not sure what the Google cloud equivalent of Microsoft WAP is, but if there is an internal firewall in-place, you will need to tell it to allow Prometheus to communicate with the other pods/components in the cluster.

**Comment by DomR22** [comment]
Hi @gsmith-sas ,

Yes i've tried a lot of times to deploy the monitoring stuck included the deploy_monitoring_viya.sh but also Kubernetes Cluster not show any metrics. Do you think that are a problem with firewall from Prometheus to other GKE components? If yes, can you pleas explain me which ports/network must be opened so i can forward these informations to the customer? Unfortunately we can't manage the GKE cluster due to customer security policies.

**Comment by gsmith-sas** [comment]
@DomR22 I just noticed that in the 1st screenshot you shared, Grafana is reporting that there are no datasources found.  This is odd since a Prometheus datasource (within Grafana) should have been created automatically as part of the deployment process.  We had a bug in our 1.2.23 (March) release that caused this problem for some customers.  However, that was fixed in our 1.2.24 (current) version which was release on 16APR24.  

Please check to see if the datasource was created by choosing Connections -> Datasources from the main menu within Grafana.  The datasource should be called Prometheus.  If the datasource is there, please select it and click on the **Save & Test** button (near the bottom of the configuration page).

If the datasource is not there, you can manually create it using the following steps:

- Log into Grafana
- Select **Connections** from the "hamburger" (three horizontal lines) menu 
- Select **Data sources** from menu along left side
- Click blue button labeled **Add new data source**
- Select **Prometheus** from the list of Time series databases
- Change the name of the data source to "**_Prometheus_**" if it isn't already that
- Enter "**_https://v4m-prometheus:9090/prometheus_**" into the Prometheus server URL box 
- Check the checkbox labeled "**Skip TLS certificate validation**"
- Scroll down and click on the button labeled **Save & Test**
- If you don't see an error after that, things should be set up properly.  

If the **Save & Test** button doesn't work, it means that Grafana cannot talk with Prometheus.  And a firewall blocking access _could_ the an issue.

In addition, the "deadline exceeded" messages shown in your last screen shot also point to to some major networking issue such as a firewall.  That screenshot comes from the Prometheus web application so it cannot be a misconfiguration of Grafana such as a missing datasource.  Prometheus is generally able to connect to a component and collect the metrics fairly quickly.  And, if you are seeing that same message for _every_ serviceMonitor and podMonitor, that also seems to point to a fundamental issue such as a firewall.

Unfortunately, it is not easy to compile a list of hosts and ports that need to be added to the firewall "permit access" list.  There are generally 100+ components that Prometheus must collect metrics from.  Each is accessed via an internal IP address that is assigned by Kubernetes and may change over time.  In theory, you could review the Targets page within Prometheus (as you did to get the 3rd screenshot) and collect all of the IP addresses and port numbers Prometheus is trying to access.  But that isn't a very feasible solution.  When working on this sort of problem in the past, we found it easier to have the security admins review the firewall logs to identify activity that was blocked incorrectly and adjust the firewall configuration to permit access.  

You could try to use `curl` from a pod within the Kubernetes cluster to access the one or more of the metric endpoints.  That _might_ provide more information about why Prometheus cannot access metrics.  For example, the following command shows how to execute a curl command (from the Grafana pod) to access metrics from one of the Java microservices in my test environment:
 `kubectl -n monitoring exec v4m-grafana-6dbdd84c89-6wcwg -it -- curl -k "https://10.254.69.255:10445/internal/metrics"`

Note that the name of the Grafana pod and the IP address of the target pod will be different in your environment.  You can use a `kubectl get pods -n monitoring` command to get the name of the Grafana pod in your cluster.  And you can review the Targets panel of the Prometheus web application (as you did in your 3rd screenshot) to find an IP address and port from in your SAS Viya deployment to target.  I would suggest trying 2 or 3 different targets to be thorough.

Finally, I would encourage you to reach out to the security admins and ask them to confirm that they are seeing messages indicating that Prometheus is being blocked.  If they are NOT seeing any sign of things being blocked, you may need to explore other possible causes.  But, I'm not sure what those other causes might be.  Problems with your TLS certificates might be the next thing to investigate if firewall issues have been ruled out. 

Please let us know how it goes.

**Comment by DomR22** [comment]
Hi @gsmith-sas ,

Yes, in version 1.2.23 I noticed that in the datasource configuration Prometheus was not loaded so I updated to 1.2.24 where it was loaded correctly but the network problem is still present, we asked the GKE admin to check the network part to allow traffic between Prometheus and the other PODs/Services in the cluster. I'll kepp you in touch!

Thanks a lot for the support!

**Comment by DomR22** [comment]
Hi @gsmith-sas ,

I'll close the issue because the GKE admin allow the traffic from monitoring namespace to Viya4 namespace and now Prometheus is able to send the metrics to grafana, thanks a lot for your help!
